site_name: H2O Healthcare 

theme:
  name: material
  logo: assets/h2o_logo/h2oai.png
  font:
    text: Roboto
  features:
    - navigation.top
    - search.suggest
  palette:
    - scheme: default
      primary: black
      toggle:
        icon: material/weather-night
    - scheme: slate
      primary: black
      toggle:
        icon: material/weather-sunny
  plugins:
    - search
extra:
  version:
    provider: mike



markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde

extra_css:
  - stylesheets/extra.css


plugins:
  - search
  - macros


extra:
  number: version_of_app_with_out_v


copyright: ©Copyright 2017-2021 H2O.ai


nav:
    - H2O Healthcare Documentation: 'index.md'
    - Overview: 
        - 'Introduction': 'introduction.md'
        - 'What is H2O Healthcare?': 'what_is_h2o_healthcare.md'
        - 'Video: H2O Healthcare Overview': 'video_h2o_healthcare_overview.md'
    - Quickstart:
        - 'Access H2O Healthcare Apps ': 'access_h2o_healthcare_apps.md'
    - H2O Healthcare Apps: 
        - 'Epidemiology AI': 
          - 'COVID-19 Forecast': 
            - 'Overview': 'epidemiology_ai_apps/covid_19_forecast/covid_19_forecast_overview.md'
            - 'Guide': 'epidemiology_ai_apps/covid_19_forecast/covid_19_forecast_guide.md'
            - 'Release Notes': 'epidemiology_ai_apps/covid_19_forecast/covid_19_forecast_release_notes.md'
            - 'FAQ': 'epidemiology_ai_apps/covid_19_forecast/covid_19_forecast_faq.md' 
          - 'COVID-19 Hospitalization Predictor':  
            - 'Overview': 'epidemiology_ai_apps/covid_19_hospitalization_predictor/covid_19_hospitalization_predictor_overview.md' 
            - 'Guide': 'epidemiology_ai_apps/covid_19_hospitalization_predictor/covid_19_hospitalization_predictor_guide.md'
            - 'Release Notes': 'epidemiology_ai_apps/covid_19_hospitalization_predictor/covid_19_hospitalization_predictor_release_notes.md' 
            - 'FAQ': 'epidemiology_ai_apps/covid_19_hospitalization_predictor/covid_19_hospitalization_predictor_faq.md' 
          - 'Pop-up Predictor':
            - 'Overview': 'epidemiology_ai_apps/pop_up_predictor/pop_up_predictor_overview.md'
            - 'Guide': 'epidemiology_ai_apps/pop_up_predictor/pop_up_predictor_guide.md'
            - 'Release Notes': 'epidemiology_ai_apps/pop_up_predictor/pop_up_predictor_release_notes.md'
            - 'FAQ': 'epidemiology_ai_apps/pop_up_predictor/pop_up_predictor_faq.md'
          - 'COVID-19 Vaccine NLP':
            - 'Overview': 'epidemiology_ai_apps/covid_19_vaccine_nlp/covid_19_vaccine_nlp_overview.md'
            - 'Guide': 'epidemiology_ai_apps/covid_19_vaccine_nlp/covid_19_vaccine_nlp_guide.md'
            - 'Release Notes': 'epidemiology_ai_apps/covid_19_vaccine_nlp/covid_19_vaccine_nlp_release_notes.md'
            - 'FAQ': 'epidemiology_ai_apps/covid_19_vaccine_nlp/covid_19_vaccine_nlp_faq.md'
    - FAQ: 'faq.md'



 




        
  
        


